LEFT_CHASSIS_MOTORS = [1, 2]
RIGHT_CHASSIS_MOTORS = [3, 4]

TURRET_CLOCKWISE_LIMIT_SWITCH = 0
TURRET_COUNTERCLOCKWISE_LIMIT_SWITCH = 1
TURRET_TURN_MOTOR = 5
TURRET_HOOD_MOTOR = 6
TURRET_SHOOT_MOTORS = [7, 8]

MAGAZINE_FEED_MOTOR = 9
MAGAZINE_LEFT_MOTOR = 10
MAGAZINE_RIGHT_MOTOR = 11
MAGAZINE_INTAKE_MOTOR = 12

INTAKE_MOTOR = 13
INTAKE_SOLENOID_DEPLOY = 1
INTAKE_SOLENOID_RETRACT = 6

ELEVATOR_MOTOR = 14

TRACKWIDTH = 0.6477
RAMSETE_MAX_VELOCITY = 4
RAMSETE_MAX_ACCELERATION = 3

PCM_ID = 19

kS = 0.333
kV = 4.06
kA = 0.118
